# Generated by Django 4.1.4 on 2023-02-04 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_recipe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='last_used',
            field=models.DateField(default=datetime.date(2023, 2, 3)),
        ),
    ]
