# Generated by Django 4.1.4 on 2023-02-04 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_recipe_last_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='last_used',
            new_name='last_made',
        ),
    ]
