# Generated by Django 4.1.4 on 2023-02-04 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='last_made',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
