# Generated by Django 4.1.4 on 2023-02-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_recipe_recipe_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/recipes'),
        ),
    ]
