# Generated by Django 4.1.4 on 2023-02-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_recipe_recipe_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='summary',
            new_name='description',
        ),
        migrations.AddField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, help_text='Enter a brief biography', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='words',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
