# Generated by Django 4.1.4 on 2023-02-04 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_rename_summary_recipe_description_author_biography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_pdf',
            field=models.FileField(help_text='Or, if you prefer, upload a pdf here.', null=True, upload_to='catalog/static/media/recipes/pdfs'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.author'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.ManyToManyField(blank=True, default=None, help_text='Select a cuisine for this recipe', to='catalog.cuisine'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='testing 213', help_text='Enter a brief description of the recipe', max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diet',
            field=models.ManyToManyField(blank=True, default=None, help_text='Select a diet for this recipe', to='catalog.diet'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_photo',
            field=models.ImageField(help_text='Upload an image of the recipe here', null=True, upload_to='catalog/static/media/recipes/images'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='testing 0.3007415587581026', max_length=200),
        ),
    ]
