# Generated by Django 4.1.6 on 2023-02-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_recipe_recipe_pdf_alter_recipe_recipe_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='testing 0.10364067406789179', max_length=200),
        ),
    ]
