# Generated by Django 4.1.6 on 2023-02-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_recipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='testing 0.060369887358472485', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='words',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
